export type PaymentProvider = 'stripe' | 'whop' | 'fanbasis'
export type PaymentRecoveryClassification = 'retryable_failure' | 'payment_method_required' | 'authentication_required' | 'secure_payment_link' | 'human_review'
export type PaymentRecoveryStatus = 'retry_in_progress' | 'payment_method_required' | 'authentication_required' | 'secure_payment_link_required' | 'promise_pending' | 'human_intervention' | 'recovered' | 'closed_unrecovered'
export type RecoveryReplyIntent = 'payment_link' | 'promise_to_pay' | 'retry_request' | 'payment_method_update' | 'payment_question' | 'hardship' | 'dispute_or_refund' | 'wrong_contact' | 'opt_out' | 'already_paid' | 'unclear'
export type RecoveryTemplate = { sms: string; emailSubject: string; emailBody: string }
export type RecoveryPolicy = { businessName: string; senderName: string; senderEmail: string; senderPhone: string; defaultOwner: string; timezone: string; escalationDays: number; maxTouches: number; followUpDelaysHours: number[]; promiseGraceHours: number; tone: 'warm' | 'direct' | 'formal'; templates: Record<PaymentRecoveryClassification, RecoveryTemplate>; templatesApprovedAt?: string; templatesApprovedBy?: string }
export type PilotValidation = { monthlyFee: number; startedAt?: string; baselineWindowDays: number; historicEligibleBalance: number; historicRecoveredAmount: number; onboardingMinutes: number; supportMinutes: number; renewalStatus: 'not_asked' | 'yes' | 'no' | 'undecided'; notes: string; updatedAt?: string; updatedBy?: string }
export type RecoveryAttempt = { id: string; channel: 'sms' | 'email' | 'call' | 'note'; direction: 'outbound' | 'inbound' | 'internal'; summary: string; body?: string; providerMessageId?: string; conversationId?: string; intent?: RecoveryReplyIntent; simulated?: boolean; createdAt: string; createdBy: string }
export type PromiseToPay = { id: string; amount: number; dueAt: string; note?: string; status: 'pending' | 'kept' | 'missed' | 'cancelled'; createdAt: string; createdBy: string }
export type RecoverySuggestion = { id: string; triggerAttemptId?: string; followUpId?: string; intent: RecoveryReplyIntent; confidence: number; recommendedAction: string; channel: 'sms' | 'email'; subject?: string; body: string; status: 'draft' | 'sent' | 'dismissed' | 'escalated'; createdAt: string; updatedAt: string }
export type RecoveryFollowUp = { id: string; kind: 'no_response' | 'promise_due'; channel: 'sms' | 'email'; dueAt: string; status: 'scheduled' | 'due' | 'completed' | 'cancelled'; attemptNumber: number; reason: string; createdAt: string; completedAt?: string }
export type PaymentRecoveryCase = { id: string; provider: PaymentProvider; sourcePaymentId: string; customerName: string; customerEmail?: string; customerPhone?: string; owner: string; amountDue: number; totalOutstanding: number; currency: string; dueAt?: string; failureCode?: string; failureReason?: string; attemptCount: number; nextRetryAt?: string; hostedPaymentUrl?: string; classification: PaymentRecoveryClassification; status: PaymentRecoveryStatus; priority: 'critical' | 'high' | 'medium'; recommendedAction: string; attempts: RecoveryAttempt[]; promises: PromiseToPay[]; suggestions: RecoverySuggestion[]; followUps: RecoveryFollowUp[]; conversationId?: string; lastInboundAt?: string; lastOutboundAt?: string; escalationReason?: string; outcome?: { type: string; amount: number; note?: string; recordedAt: string; recordedBy: string }; createdAt: string; updatedAt: string; recoveredAt?: string }
export type RecoveryReport = { totalOverdue: number; eligibleBalance: number; contactedCases: number; responseRate: number; promisesMade: number; promisesKept: number; cashRecovered: number; medianRecoveryHours: number; humanEscalationRate: number; replyNeeded: number; followUpsDue: number; promisesDue: number; assistedRepliesSent: number; recoveredAfterAssistance: number; byClassification: Record<string, { cases: number; recovered: number }> }
export type PaymentRecoverySnapshot = { cases: PaymentRecoveryCase[]; policy: RecoveryPolicy; pilotValidation: PilotValidation; report: RecoveryReport; sources: Array<{ id: PaymentProvider; connected: boolean; mode?: string; sample?: boolean }> }

export async function recoveryApi<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } })
  const body = await response.json().catch(() => ({})) as T & { error?: string }
  if (!response.ok) throw new Error(body.error ?? `Request failed with status ${response.status}.`)
  return body
}
